#include "entity/player/EntityPlayerMPStats.h"
#include "util/MCGameplayCrafting.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks;
#define CHECK(x) do{++checks;if(!(x)){fprintf(stderr,"MP stats check %u line %d: %s\n",checks,__LINE__,#x);exit(1);}}while(0)
typedef struct {MCObject object;int32_t points;bool force,readOnly;unsigned notifications;} WitnessScore;
typedef struct {MCObject object;MCObject *values[2];size_t length;} Objectives;
typedef struct {MCObject object;Objectives *list;size_t next;} Iterator;
typedef struct {
    MCObject object;StatisticsFile *file;MCGameplayPlayer *player;StatBase *stat;NBTString *name;
    WitnessScore *scores[2];Objectives *objectives;StatisticsFileIntMap *sent;unsigned sends,chats,taken;
    char events[256];size_t used;unsigned calls,failAt;int32_t tick;bool announce;
    char scoreEvents[32];size_t scoreUsed;
} Context;
static void objectives_trace(MCObject *o,MCObjectVisitor v,void *c){Objectives *l=(Objectives *)o;for(size_t i=0;i<2;i++)l->values[i]=v(l->values[i],c);}
static void iterator_trace(MCObject *o,MCObjectVisitor v,void *c){Iterator *i=(Iterator *)o;i->list=(Objectives *)v((MCObject *)i->list,c);}
static void context_trace(MCObject *o,MCObjectVisitor v,void *c){Context *x=(Context *)o;x->file=(StatisticsFile *)v((MCObject *)x->file,c);x->player=(MCGameplayPlayer *)v((MCObject *)x->player,c);x->stat=(StatBase *)v((MCObject *)x->stat,c);x->name=(NBTString *)v((MCObject *)x->name,c);x->objectives=(Objectives *)v((MCObject *)x->objectives,c);x->sent=(StatisticsFileIntMap *)v((MCObject *)x->sent,c);for(size_t i=0;i<2;i++)x->scores[i]=(WitnessScore *)v((MCObject *)x->scores[i],c);}
static const MCObjectClass score_class={"fixture.WitnessScore",MCObjectHeap_plainClone,NULL,NULL},objectives_class={"fixture.objectives",MCObjectHeap_plainClone,objectives_trace,NULL},iterator_class={"fixture.iterator",MCObjectHeap_plainClone,iterator_trace,NULL},context_class={"fixture.stats dependencies",MCObjectHeap_plainClone,context_trace,NULL};
static bool event(Context *c,char ch){CHECK(MCObjectHeap_hasBorrowers(c->object.heap)&&!MCObjectHeap_collect(c->object.heap));CHECK(c->used+1<sizeof(c->events));c->events[c->used++]=ch;c->events[c->used]=0;c->calls++;MCObjectHeap_touch(c->object.heap);if(c->failAt==c->calls){MCObjectHeap_fail(c->object.heap);return false;}return true;}
static void score_event(Context *c,char ch){CHECK(c->scoreUsed+1<sizeof(c->scoreEvents));c->scoreEvents[c->scoreUsed++]=ch;c->scoreEvents[c->scoreUsed]=0;MCObjectHeap_touch(c->object.heap);}
static bool announcing(MCObject *o,MCObject *server){Context *c=(Context *)o;CHECK(server==o);return event(c,'A')&&c->announce;}
static bool chat(MCObject *o,MCObject *server,MCObject *player,StatBase *stat,bool taken){Context *c=(Context *)o;CHECK(server==o&&player==(MCObject *)c->player&&stat==c->stat);if(!event(c,taken?'R':'U'))return false;c->chats++;c->taken+=taken;return true;}
static int32_t tick(MCObject *o,MCObject *server){CHECK(server==o);Context *c=(Context *)o;event(c,'T');return c->tick;}
static bool send_stats(MCObject *o,MCObject *player,StatisticsFileIntMap *map){Context *c=(Context *)o;CHECK(player==(MCObject *)c->player&&map);if(!event(c,'S'))return false;c->sent=map;c->sends++;return true;}
static const StatisticsFileDependencies file_dependencies={announcing,chat,tick,send_stats};
static MCObject *board(MCObject *o,MCGameplayPlayer *p){Context *c=(Context *)o;CHECK(p==c->player);return event(c,'B')?o:NULL;}
static MCObject *criteria(MCObject *o,StatBase *s){Context *c=(Context *)o;CHECK(s==c->stat);return event(c,'C')?(MCObject *)s:NULL;}
static MCObject *objectives(MCObject *o,MCObject *board,MCObject *criterion){Context *c=(Context *)o;CHECK(board==o&&criterion==(MCObject *)c->stat);if(!event(c,'O'))return NULL;score_event(c,'O');return (MCObject *)c->objectives;}
static MCObject *iterator(MCObject *o,MCObject *list){Context *c=(Context *)o;CHECK(list==(MCObject *)c->objectives);if(!event(c,'I'))return NULL;Iterator *i=(Iterator *)MCObjectHeap_alloc(o->heap,sizeof(*i),&iterator_class);if(i)i->list=(Objectives *)list;return (MCObject *)i;}
static bool has_next(MCObject *o,MCObject *it){Context *c=(Context *)o;Iterator *i=(Iterator *)it;return event(c,'?')&&i->next<i->list->length;}
static MCObject *next(MCObject *o,MCObject *it){Context *c=(Context *)o;Iterator *i=(Iterator *)it;CHECK(i->next<i->list->length);return event(c,'N')?i->list->values[i->next++]:NULL;}
static NBTString *name(MCObject *o,MCGameplayPlayer *p){Context *c=(Context *)o;CHECK(p==c->player);return event(c,'P')?c->name:NULL;}
static MCObject *get_score(MCObject *o,MCObject *board,const NBTString *name,MCObject *objective){Context *c=(Context *)o;CHECK(board==o&&name==c->name);if(!event(c,'V'))return NULL;score_event(c,'V');CHECK(objective==(MCObject *)c->scores[0]||objective==(MCObject *)c->scores[1]);return objective;}
static bool set_score(MCObject *o,MCObject *object,int32_t points){Context *c=(Context *)o;WitnessScore *s=(WitnessScore *)object;if(!event(c,'='))return false;int32_t old=s->points;s->points=points;if(old!=points||s->force){s->force=false;s->notifications++;score_event(c,'D');}MCObjectHeap_touch(o->heap);return true;}
static bool increase(MCObject *o,MCObject *object,int32_t amount){Context *c=(Context *)o;WitnessScore *s=(WitnessScore *)object;if(!event(c,'+'))return false;if(s->readOnly){MCObjectHeap_fail(o->heap);return false;}uint32_t b=(uint32_t)s->points+(uint32_t)amount;int32_t value;memcpy(&value,&b,sizeof(value));return set_score(o,object,value);}
static const EntityPlayerMPStatsDependencies mp_dependencies={board,criteria,objectives,iterator,has_next,next,name,get_score,increase,set_score};
static NBTString *display(MCObject *o,const ItemStack *s){(void)s;return ((Context *)o)->name;}
static bool uncalled_craft(ItemStack *s,MCObject *w,MCObject *p,int32_t n){(void)s;(void)w;(void)n;MCObjectHeap_fail(p->heap);return false;}
static bool uncalled_achievement(MCObject *p,mc_crafting_achievement a){(void)a;MCObjectHeap_fail(p->heap);return false;}
static bool uncalled_drop(MCObject *p,ItemStack *s,bool b){(void)s;(void)b;MCObjectHeap_fail(p->heap);return false;}
static const MCGameplayCraftingEffects effects={uncalled_craft,uncalled_achievement,uncalled_drop};
typedef struct {MCGameplay game;Context *context;mc_crafting_dispatch dispatch;MCObjectRootScope scope;} Fixture;
static void init(Fixture *f){memset(f,0,sizeof(*f));CHECK(MCGameplay_init(&f->game,64*1024*1024)&&MCObjectRootScope_begin(&f->scope,f->game.heap));MCObjectHeap *h=f->game.heap;Context *c=(Context *)MCObjectHeap_alloc(h,sizeof(*c),&context_class);CHECK(c);f->context=c;c->name=NBTString_fromASCII(h,"stats-player");CHECK(c->name);MCGameplayWorld *w=MCGameplayWorld_new(h,MCGameplay_get(&f->game),NULL,NULL);CHECK(w&&MCGameplay_setWorld(&f->game,(MCObject *)w)&&MCGameplayCrafting_configureWorld(w,display,(MCObject *)c));c->file=StatisticsFile_nativeNew(h,(MCObject *)c,NBTString_fromASCII(h,"stats.json"),(MCObject *)c,&file_dependencies);CHECK(c->file);CHECK(MCGameplayCrafting_nativeDispatch(&f->dispatch,&effects));c->player=MCGameplayPlayer_new(w,c->name,&c->file->base,&f->dispatch);CHECK(c->player&&MCGameplay_setPlayer(&f->game,0,"11111111-1111-1111-1111-111111111111",(MCObject *)c->player));c->player->effects=(MCObject *)c;c->objectives=(Objectives *)MCObjectHeap_alloc(h,sizeof(*c->objectives),&objectives_class);CHECK(c->objectives);c->objectives->length=2;for(size_t i=0;i<2;i++){c->scores[i]=(WitnessScore *)MCObjectHeap_alloc(h,sizeof(WitnessScore),&score_class);CHECK(c->scores[i]);c->scores[i]->force=true;c->objectives->values[i]=(MCObject *)c->scores[i];}c->stat=StatBase_newIdentity(h,NBTString_fromASCII(h,"native.counter"),STAT_BASE_KIND_BASE);CHECK(c->stat);}
static void finish(Fixture *f){MCObjectRootScope_end(&f->scope);CHECK(MCGameplay_free(&f->game));}
static void reset_log(Context *c){c->used=c->calls=c->scoreUsed=0;c->events[0]=c->scoreEvents[0]=0;}
static void ordinary_and_null(void){CHECK(EntityPlayerMP_addStat(NULL,NULL,INT32_MIN,NULL,NULL)&&EntityPlayerMP_func_175145_a(NULL,NULL,NULL,NULL));Fixture f;init(&f);Context *c=f.context;CHECK(!StatisticsFile_func_150879_e(c->file)&&c->file->field_150885_f==-300);CHECK(EntityPlayerMP_addStat(c->player,c->stat,5,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==5);CHECK(c->scores[0]->points==5&&c->scores[1]->points==5&&c->scores[0]->notifications==1&&c->scores[1]->notifications==1);CHECK(strcmp(c->events,"BCOI?NBPV+=?NBPV+=?")==0&&!c->sends&&!c->chats);CHECK(StatisticsFileStatSet_size(c->file->field_150888_e)==1);reset_log(c);CHECK(EntityPlayerMP_addStat(c->player,c->stat,0,(MCObject *)c,&mp_dependencies));CHECK(c->scores[0]->notifications==1&&c->scores[1]->notifications==1);reset_log(c);CHECK(EntityPlayerMP_func_175145_a(c->player,c->stat,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==0&&c->scores[0]->points==0&&c->scores[0]->notifications==2);CHECK(strcmp(c->events,"BCOI?NBPV=?NBPV=?")==0&&!c->sends);CHECK(!MCObjectHeap_failed(f.game.heap));finish(&f);}
static void achievement_gate_and_dirty(void){Fixture f;init(&f);Context *c=f.context;MCObjectHeap *h=f.game.heap;Achievement *parent=Achievement_newIdentity(h,NBTString_fromASCII(h,"native.parent"),NULL),*child=Achievement_newIdentity(h,NBTString_fromASCII(h,"native.child"),parent);CHECK(parent&&child);c->stat=&child->base;CHECK(EntityPlayerMP_addStat(c->player,c->stat,3,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_statCount(&c->file->base)==0&&c->scores[0]->points==3&&!c->sends&&!StatisticsFileStatSet_size(c->file->field_150888_e));CHECK(StatFileWriter_unlockAchievementBase(&c->file->base,NULL,&parent->base,1));reset_log(c);c->announce=true;CHECK(EntityPlayerMP_addStat(c->player,c->stat,1,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==1&&c->chats==1&&c->sends==1&&c->scores[0]->points==4);CHECK(strcmp(c->events,"AUBCOI?NBPV+=?NBPV+=?TS")==0);CHECK(!StatisticsFile_func_150879_e(c->file)&&StatisticsFileStatSet_size(c->file->field_150888_e)==0&&StatisticsFileIntMap_size(c->sent)==1);StatBase *key;int32_t value;CHECK(StatisticsFileIntMap_entry(c->sent,0,&key,&value)&&key==c->stat&&value==1);reset_log(c);CHECK(EntityPlayerMP_func_175145_a(c->player,c->stat,(MCObject *)c,&mp_dependencies));CHECK(c->chats==2&&c->taken==1&&c->sends==2&&strcmp(c->events,"ARBCOI?NBPV=?NBPV=?TS")==0);CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==0&&c->scores[0]->points==0);CHECK(!MCObjectHeap_failed(h));finish(&f);}
static void dirty_tick_boundaries(void){Fixture f;init(&f);Context *c=f.context;CHECK(StatFileWriter_increaseStat(&c->file->base,(MCObject *)c->player,c->stat,9));CHECK(StatisticsFile_func_150876_a(c->file,(MCObject *)c->player));CHECK(c->sends==1&&StatisticsFileIntMap_size(c->sent)==0&&StatisticsFileStatSet_size(c->file->field_150888_e)==1&&c->file->field_150885_f==-300);c->tick=1;CHECK(StatisticsFile_func_150876_a(c->file,(MCObject *)c->player));CHECK(c->sends==2&&StatisticsFileIntMap_size(c->sent)==1&&c->file->field_150885_f==1);CHECK(StatisticsFile_func_150877_d(c->file)&&StatisticsFileStatSet_size(c->file->field_150888_e)==1);StatisticsFileStatSet *set=StatisticsFile_func_150878_c(c->file);CHECK(set&&StatisticsFileStatSet_size(set)==1&&StatisticsFileStatSet_get(set,0)==c->stat&&StatisticsFileStatSet_size(c->file->field_150888_e)==0);CHECK(StatFileWriter_increaseStat(&c->file->base,(MCObject *)c->player,c->stat,0));c->file->field_150885_f=INT32_MIN;c->tick=INT32_MAX;CHECK(StatisticsFile_func_150876_a(c->file,(MCObject *)c->player));CHECK(StatisticsFileIntMap_size(c->sent)==0&&StatisticsFileStatSet_size(c->file->field_150888_e)==1&&c->file->field_150885_f==INT32_MIN);c->file->field_150885_f=INT32_MAX;c->tick=INT32_MIN+300;CHECK(StatisticsFile_func_150876_a(c->file,(MCObject *)c->player));CHECK(StatisticsFileIntMap_size(c->sent)==1&&c->file->field_150885_f==INT32_MIN+300);CHECK(StatisticsFileStatSet_size(set)==1&&!MCObjectHeap_failed(f.game.heap));finish(&f);}
static void failures_and_snapshot(void){for(unsigned at=1;at<=19;at++){Fixture f;init(&f);Context *c=f.context;c->failAt=at;CHECK(!EntityPlayerMP_addStat(c->player,c->stat,4,(MCObject *)c,&mp_dependencies));CHECK(MCObjectHeap_failed(f.game.heap)&&c->calls==at);finish(&f);}Fixture f;init(&f);Context *c=f.context;c->scores[0]->readOnly=true;CHECK(!EntityPlayerMP_addStat(c->player,c->stat,4,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==0);/* Heap error blocks further reads; source state still records the attempted counter in the branch. */CHECK(c->scores[0]->points==0&&c->scores[1]->points==0&&StatisticsFileStatSet_size(c->file->field_150888_e)==1);finish(&f);
    init(&f);c=f.context;CHECK(EntityPlayerMP_addStat(c->player,c->stat,4,(MCObject *)c,&mp_dependencies));MCObjectRootScope_end(&f.scope);MCGameplayTransaction tx={0};CHECK(MCGameplay_begin(&f.game,&tx));MCGameplayPlayer *p=(MCGameplayPlayer *)MCGameplay_get(&tx.working)->players[0];Context *cc=(Context *)p->effects;CHECK(cc!=c&&cc->file!=(StatisticsFile *)c->player->stats&&p->stats==&cc->file->base&&cc->file->dependencyContext==(MCObject *)cc&&cc->file->mcServer==(MCObject *)cc);CHECK(EntityPlayerMP_func_175145_a(p,cc->stat,(MCObject *)cc,&mp_dependencies));CHECK(c->scores[0]->points==4&&cc->scores[0]->points==0&&StatFileWriter_readStat(&c->file->base,c->stat)==4&&StatFileWriter_readStat(&cc->file->base,cc->stat)==0);CHECK(MCGameplay_abort(&tx)&&!MCObjectHeap_failed(f.game.heap));finish(&f);}
static void tuple_map_alias(void){MCObjectHeap *h=MCObjectHeap_new(4*1024*1024);CHECK(h);StatFileWriter *a=StatFileWriter_new(h),*b=StatFileWriter_new(h);StatBase *first=StatBase_newIdentity(h,NBTString_fromASCII(h,"same"),STAT_BASE_KIND_BASE),*equal=StatBase_newIdentity(h,NBTString_fromASCII(h,"same"),STAT_BASE_KIND_BASE);CHECK(a&&b&&first&&equal);CHECK(StatFileWriter_unlockAchievementBase(a,NULL,first,7)&&StatFileWriter_unlockAchievementBase(b,NULL,equal,11));CHECK(StatFileWriter_putAll(a,b));StatBase *key=NULL;CHECK(StatFileWriter_entryAt(a,0,&key,NULL,NULL)&&key==first&&StatFileWriter_readStat(a,first)==11);CHECK(StatFileWriter_unlockAchievementBase(b,NULL,equal,19)&&StatFileWriter_readStat(a,first)==19);CHECK(StatFileWriter_clear(b)&&StatFileWriter_readStat(a,first)==19&&StatFileWriter_statCount(b)==0);CHECK(StatFileWriter_putAll(a,a)&&!MCObjectHeap_failed(h));MCObjectHeap_free(h);}
static void arithmetic(bool print){const int32_t amounts[]={INT32_MIN,-3,-1,0,1,4,INT32_MAX},initials[]={INT32_MIN,-1,0,1,INT32_MAX};for(size_t i=0;i<sizeof(initials)/sizeof(*initials);i++)for(size_t j=0;j<sizeof(amounts)/sizeof(*amounts);j++){Fixture f;init(&f);Context *c=f.context;for(size_t k=0;k<2;k++){c->scores[k]->points=initials[i];c->scores[k]->force=false;}CHECK(EntityPlayerMP_addStat(c->player,c->stat,amounts[j],(MCObject *)c,&mp_dependencies));uint32_t b=(uint32_t)initials[i]+(uint32_t)amounts[j];int32_t value;memcpy(&value,&b,sizeof(value));CHECK(c->scores[0]->points==value&&c->scores[1]->points==value&&StatFileWriter_readStat(&c->file->base,c->stat)==amounts[j]);unsigned boards=0,names=0;for(size_t n=0;n<c->used;n++){boards+=c->events[n]=='B';names+=c->events[n]=='P';}CHECK(boards==3&&names==2);if(print)printf("%d %d %d %d %d %u %u %u %s\n",initials[i],amounts[j],StatFileWriter_readStat(&c->file->base,c->stat),c->scores[0]->points,c->scores[1]->points,c->scores[0]->notifications+c->scores[1]->notifications,names,boards,c->scoreEvents);reset_log(c);CHECK(EntityPlayerMP_func_175145_a(c->player,c->stat,(MCObject *)c,&mp_dependencies));CHECK(StatFileWriter_readStat(&c->file->base,c->stat)==0&&c->scores[0]->points==0&&c->scores[1]->points==0&&!MCObjectHeap_failed(f.game.heap));finish(&f);}}
int main(int argc,char **argv){if(argc==2&&strcmp(argv[1],"--facts")==0){arithmetic(true);return 0;}ordinary_and_null();achievement_gate_and_dirty();dirty_tick_boundaries();failures_and_snapshot();tuple_map_alias();arithmetic(false);printf("source MP statistics: %u checks\n",checks);return 0;}
