#include "item/crafting/RecipesBanners.h"
#include "item/crafting/CraftingManager.h"
#include "tileentity/TileEntityBanner.h"
#include "nbt/NBTTagCompound.h"
#include "nbt/NBTTagString.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks;
#define CHECK(x) do {++checks;if(!(x)){fprintf(stderr,"banner check %u line %d: %s\n",checks,__LINE__,#x);exit(1);}} while(0)
static bool changed(MCObject *o,InventoryCrafting *g) {(void)o;(void)g;return true;}
static const MCObjectClass eventClass={"banner unit matrix notification fixture",MCObjectHeap_plainClone,NULL,NULL};
static InventoryCrafting *grid(MCObjectHeap *h,int32_t width) {MCObject *event=MCObjectHeap_alloc(h,sizeof(MCObject),&eventClass);CHECK(event);InventoryCrafting *g=InventoryCrafting_new(h,event,changed,width,width);CHECK(g);return g;}
static ItemStack *item(MCObjectHeap *h,int32_t id,int32_t n,int32_t damage) {ItemStack *s=ItemStack_new(h,ItemStack_registryItem(id),n,damage);CHECK(s);return s;}
static void put(InventoryCrafting *g,int32_t i,ItemStack *s) {CHECK(InventoryCrafting_setInventorySlotContents(g,i,s));}
static void clear(InventoryCrafting *g) {for(int32_t i=0;i<InventoryCrafting_getSizeInventory(g);i++)put(g,i,NULL);}
static NBTTagCompound *block_tag(ItemStack *s) {NBTString *key=NBTString_literalASCII(s->object.heap,"BlockEntityTag");CHECK(key);NBTTagCompound *b=ItemStack_getSubCompound(s,key,true);CHECK(b);return b;}
static NBTTagList *patterns(ItemStack *s,int32_t n) {NBTTagCompound *b=block_tag(s);NBTTagList *l=NBTTagList_new(s->object.heap);CHECK(l);CHECK(NBTTagCompound_setTag_ascii(b,"Patterns",(NBTBase *)l));for(int32_t i=0;i<n;i++){NBTTagCompound *p=NBTTagCompound_new(s->object.heap);CHECK(p);CHECK(NBTTagCompound_setString_ascii(p,"Pattern",NBTString_fromASCII(s->object.heap,"bs")));CHECK(NBTTagCompound_setInteger_ascii(p,"Color",1));CHECK(NBTTagList_appendTag(l,(NBTBase *)p));}return l;}
static void enums_and_roots(void) {
    MCObjectHeap *h=MCObjectHeap_new(4*1024*1024);CHECK(h);MCObjectRootScope scope={0};CHECK(MCObjectRootScope_begin(&scope,h));
    EnumBannerPatternArray *a=EnumBannerPattern_values(h),*b=EnumBannerPattern_values(h);CHECK(a&&b&&a!=b&&a->length==39&&b->length==39);CHECK(a->items[31]==b->items[31]);
    for(int32_t i=0;i<a->length;i++){EnumBannerPattern *p=a->items[i];CHECK(p&&EnumBannerPattern_getCraftingLayers(p)->length==3);CHECK(EnumBannerPattern_getPatternByID(h,EnumBannerPattern_getPatternID(p))==p);CHECK(EnumBannerPattern_hasValidCrafting(p)==(i!=0));CHECK(EnumBannerPattern_getCraftingStack(p)==p->patternCraftingStack);}
    CHECK(!EnumBannerPattern_getPatternByID(h,NBTString_fromASCII(h,"unknown")));EnumBannerPattern *saved=a->items[1];a->items[1]=NULL;CHECK(b->items[1]==saved);MCObjectHeap_touch(h);
    ItemStack *special=b->items[31]->patternCraftingStack;
    MCObjectRoot root={0};CHECK(MCObjectRoot_init(&root,h,(MCObject *)saved));MCObjectRootScope_end(&scope);CHECK(MCObjectHeap_collect(h));
    size_t baseline=MCObjectHeap_liveObjects(h);
    CHECK(MCObjectRootScope_begin(&scope,h));for(int i=0;i<100;i++){EnumBannerPatternArray *v=EnumBannerPattern_values(h);CHECK(v&&v->items[1]==saved);}MCObjectRootScope_end(&scope);CHECK(MCObjectHeap_collect(h)&&MCObjectHeap_liveObjects(h)==baseline);
    MCObjectHeap *copy=MCObjectHeap_clone(h);CHECK(copy);MCObjectRoot mapped={0};CHECK(MCObjectRoot_rebind(&mapped,copy,&root));CHECK(MCObjectRootScope_begin(&scope,copy));EnumBannerPatternArray *c=EnumBannerPattern_values(copy);CHECK(c&&c->items[1]==(EnumBannerPattern *)MCObjectRoot_get(&mapped)&&c->items[1]!=saved);CHECK(c->items[31]->patternCraftingStack!=special);MCObjectRootScope_end(&scope);MCObjectRoot_drop(&mapped);MCObjectHeap_free(copy);MCObjectRoot_drop(&root);MCObjectHeap_free(h);
}
static void add_and_mutability(void) {
    MCObjectHeap *h=MCObjectHeap_new(16*1024*1024);CHECK(h);MCObjectRootScope scope={0};CHECK(MCObjectRootScope_begin(&scope,h));InventoryCrafting *g=grid(h,3);RecipesBannersRecipeAddPattern *r=RecipesBannersRecipeAddPattern_new(h);CHECK(r);CHECK(RecipesBannersRecipeAddPattern_getRecipeSize(r)==10&&!RecipesBannersRecipeAddPattern_getRecipeOutput(r));
    /* Original special templates accept an absent dye and then choose color0. */
    static const int32_t special[][3]={{106,0,31},{397,4,32},{45,0,35},{397,1,36},{38,8,37},{322,1,38}};
    EnumBannerPatternArray *values=EnumBannerPattern_values(h);CHECK(values);
    for(size_t k=0;k<sizeof(special)/sizeof(*special);k++)for(int dye=-1;dye<16;dye++) {
        clear(g);ItemStack *banner=item(h,425,0,7);NBTTagCompound *bet=block_tag(banner);CHECK(NBTTagCompound_setInteger_ascii(bet,"custom",42));put(g,0,banner);put(g,8,item(h,special[k][0],-1,special[k][1]));if(dye>=0)put(g,4,item(h,351,127,dye));
        CHECK(RecipesBannersRecipeAddPattern_matches(r,g,NULL));ItemStack *out=RecipesBannersRecipeAddPattern_getCraftingResult(r,g);CHECK(out&&out!=banner&&out->stackSize==1&&out->itemDamage==7&&out->stackTagCompound!=banner->stackTagCompound);CHECK(TileEntityBanner_getPatterns(banner)==0&&TileEntityBanner_getPatterns(out)==1);NBTTagCompound *ob=block_tag(out);CHECK(NBTTagCompound_getInteger_ascii(ob,"custom")==42);NBTTagCompound *p=NBTTagList_getCompoundTagAt(NBTTagCompound_getTagList_ascii(ob,"Patterns",10),0);CHECK(NBTString_equals(NBTTagCompound_getString_ascii(p,"Pattern"),values->items[special[k][2]]->patternID));CHECK(NBTTagCompound_getInteger_ascii(p,"Color")== (dye<0?0:dye));
    }
    clear(g);ItemStack *source=item(h,425,9,1);put(g,0,source);put(g,6,item(h,351,1,3));CHECK(RecipesBannersRecipeAddPattern_matches(r,g,NULL));BannerStringArray *layers=values->items[1]->craftingLayers;NBTString *old=layers->items[2];layers->items[2]=NBTString_fromASCII(h,"   ");MCObjectHeap_touch(h);CHECK(!RecipesBannersRecipeAddPattern_matches(r,g,NULL));layers->items[2]=old;MCObjectHeap_touch(h);CHECK(RecipesBannersRecipeAddPattern_matches(r,g,NULL));
    patterns(source,6);CHECK(!RecipesBannersRecipeAddPattern_matches(r,g,NULL));patterns(source,5);CHECK(RecipesBannersRecipeAddPattern_matches(r,g,NULL));put(g,1,item(h,425,1,1));CHECK(!RecipesBannersRecipeAddPattern_matches(r,g,NULL));
    clear(g);source=item(h,425,1,9);put(g,0,source);put(g,8,item(h,106,1,0));NBTTagList *wrong=NBTTagList_new(h);CHECK(wrong);CHECK(NBTTagList_appendTag(wrong,(NBTBase *)NBTTagString_new(h,NBTString_fromASCII(h,"wrong"))));CHECK(NBTTagCompound_setTag_ascii(block_tag(source),"Patterns",(NBTBase *)wrong));CHECK(RecipesBannersRecipeAddPattern_matches(r,g,NULL));ItemStack *out=RecipesBannersRecipeAddPattern_getCraftingResult(r,g);CHECK(out&&TileEntityBanner_getPatterns(out)==0);CHECK(NBTTagList_getTagType(NBTTagCompound_getTagList_ascii(block_tag(out),"Patterns",8))==8);CHECK(NBTTagList_tagCount(wrong)==1);
    clear(g);put(g,0,item(h,335,1,0));ItemStackArray *rem=RecipesBannersRecipeAddPattern_getRemainingItems(r,g);CHECK(rem&&rem->items[0]&&rem->items[0]->item==ItemStack_registryItem(325)&&rem->items[0]->stackSize==1);CHECK(!MCObjectHeap_failed(h));MCObjectRootScope_end(&scope);MCObjectHeap_free(h);
}
static void duplicate_and_helpers(void) {
    MCObjectHeap *h=MCObjectHeap_new(8*1024*1024);CHECK(h);MCObjectRootScope scope={0};CHECK(MCObjectRootScope_begin(&scope,h));InventoryCrafting *g=grid(h,2);RecipesBannersRecipeDuplicatePattern *r=RecipesBannersRecipeDuplicatePattern_new(h);CHECK(r&&RecipesBannersRecipeDuplicatePattern_getRecipeSize(r)==2&&!RecipesBannersRecipeDuplicatePattern_getRecipeOutput(r));ItemStack *a=item(h,425,0,3),*b=item(h,425,-1,3);patterns(a,1);put(g,0,a);put(g,3,b);CHECK(RecipesBannersRecipeDuplicatePattern_matches(r,g,NULL));ItemStack *out=RecipesBannersRecipeDuplicatePattern_getCraftingResult(r,g);CHECK(out&&out!=a&&out->stackSize==1&&out->stackTagCompound!=a->stackTagCompound&&NBTBase_equals((NBTBase *)out->stackTagCompound,(NBTBase *)a->stackTagCompound));ItemStackArray *rem=RecipesBannersRecipeDuplicatePattern_getRemainingItems(r,g);CHECK(rem&&rem->items[0]&&rem->items[0]!=a&&rem->items[0]->stackSize==1&&!rem->items[3]);
    CHECK(NBTTagCompound_setInteger_ascii(block_tag(b),"Base",3));b->itemDamage=12;CHECK(RecipesBannersRecipeDuplicatePattern_matches(r,g,NULL));CHECK(NBTTagCompound_setString_ascii(block_tag(b),"Base",NBTString_fromASCII(h,"bad")));CHECK(TileEntityBanner_getBaseColor(b)==0&&!RecipesBannersRecipeDuplicatePattern_matches(r,g,NULL));CHECK(TileEntityBanner_getBaseColor(a)==3);
    clear(g);ItemStack *other=item(h,1,8,7);patterns(other,2);put(g,1,other);CHECK(!RecipesBannersRecipeDuplicatePattern_matches(r,g,NULL));out=RecipesBannersRecipeDuplicatePattern_getCraftingResult(r,g);CHECK(out&&out->item==other->item&&out->stackSize==1);rem=RecipesBannersRecipeDuplicatePattern_getRemainingItems(r,g);CHECK(rem&&rem->items[1]&&rem->items[1]->item==other->item&&rem->items[1]!=other);other->item=ItemStack_registryItem(335);rem=RecipesBannersRecipeDuplicatePattern_getRemainingItems(r,g);CHECK(rem&&rem->items[1]->item==ItemStack_registryItem(325));
    CHECK(!MCObjectHeap_failed(h));MCObjectRootScope_end(&scope);MCObjectHeap_free(h);
}
static void manager_and_exception(void) {
    MCObjectHeap *h=MCObjectHeap_new(8*1024*1024);CHECK(h);MCObjectRootScope scope={0};CHECK(MCObjectRootScope_begin(&scope,h));InventoryCrafting *g=grid(h,3);CraftingManager *m=CraftingManager_newEmpty(h);CHECK(m);RecipesBannersRecipeAddPattern *add=RecipesBannersRecipeAddPattern_new(h);RecipesBannersRecipeDuplicatePattern *dup=RecipesBannersRecipeDuplicatePattern_new(h);CHECK(add&&dup);CHECK(CraftingManager_addRecipe(m,RecipesBannersRecipeAddPattern_asRecipe(add)));CHECK(CraftingManager_addRecipe(m,RecipesBannersRecipeDuplicatePattern_asRecipe(dup)));
    ItemStack *a=item(h,425,2,7);put(g,0,a);put(g,6,item(h,351,4,3));ItemStack *out=CraftingManager_findMatchingRecipe(m,g,NULL,NULL,NULL);CHECK(out&&TileEntityBanner_getPatterns(out)==1);clear(g);patterns(a,2);put(g,3,a);put(g,8,item(h,425,-2,7));out=CraftingManager_findMatchingRecipe(m,g,NULL,NULL,NULL);CHECK(out&&out!=a&&out->stackSize==1&&TileEntityBanner_getPatterns(out)==2);ItemStackArray *rem=CraftingManager_func_180303_b(m,g,NULL);CHECK(rem&&rem->items[3]&&rem->items[3]!=a&&rem->items[3]->stackSize==1&&!rem->items[8]);
    MCObjectRoot managerRoot={0},gridRoot={0};CHECK(MCObjectRoot_init(&managerRoot,h,(MCObject *)m));CHECK(MCObjectRoot_init(&gridRoot,h,(MCObject *)g));MCObjectRootScope_end(&scope);MCObjectHeap *copy=MCObjectHeap_clone(h);CHECK(copy);MCObjectRoot cm={0},cg={0};CHECK(MCObjectRoot_rebind(&cm,copy,&managerRoot)&&MCObjectRoot_rebind(&cg,copy,&gridRoot));CHECK(MCObjectRootScope_begin(&scope,copy));out=CraftingManager_findMatchingRecipe((CraftingManager *)MCObjectRoot_get(&cm),(InventoryCrafting *)MCObjectRoot_get(&cg),NULL,NULL,NULL);CHECK(out&&out->object.heap==copy&&TileEntityBanner_getPatterns(out)==2);EnumBannerPatternArray *v=EnumBannerPattern_values(copy);CHECK(v&&v->items[31]->object.heap==copy&&v->items[31]->patternCraftingStack->object.heap==copy);MCObjectRootScope_end(&scope);MCObjectRoot_drop(&cm);MCObjectRoot_drop(&cg);MCObjectHeap_free(copy);MCObjectRoot_drop(&managerRoot);MCObjectRoot_drop(&gridRoot);MCObjectHeap_free(h);
    h=MCObjectHeap_new(4*1024*1024);CHECK(h);CHECK(MCObjectRootScope_begin(&scope,h));g=grid(h,3);add=RecipesBannersRecipeAddPattern_new(h);CHECK(add);put(g,0,item(h,106,1,0));CHECK(!RecipesBannersRecipeAddPattern_matches(add,g,NULL)&&!MCObjectHeap_failed(h));CHECK(!RecipesBannersRecipeAddPattern_getCraftingResult(add,g)&&MCObjectHeap_failed(h));MCObjectRootScope_end(&scope);MCObjectHeap_free(h);
}
static void original_vectors(const char *path) {
    FILE *f=fopen(path,"r");CHECK(f);unsigned vectors=0;int32_t id[9],damage[9],expected,ordinal,color;
    while(fscanf(f,"%d %d",&id[0],&damage[0])==2) {
        for(int i=1;i<9;i++) { CHECK(fscanf(f,"%d %d",&id[i],&damage[i])==2); }
        CHECK(fscanf(f,"%d %d %d",&expected,&ordinal,&color)==3);
        MCObjectHeap *h=MCObjectHeap_new(4*1024*1024);CHECK(h);MCObjectRootScope scope={0};CHECK(MCObjectRootScope_begin(&scope,h));InventoryCrafting *g=grid(h,3);RecipesBannersRecipeAddPattern *r=RecipesBannersRecipeAddPattern_new(h);CHECK(r);for(int i=0;i<9;i++)if(id[i]>=0){ItemStack *s=item(h,id[i],0,0);s->itemDamage=damage[i];put(g,i,s);}CHECK((int)RecipesBannersRecipeAddPattern_matches(r,g,NULL)==expected);ItemStack *out=RecipesBannersRecipeAddPattern_getCraftingResult(r,g);
        if(expected){CHECK(out);NBTTagList *l=NBTTagCompound_getTagList_ascii(block_tag(out),"Patterns",10);CHECK(NBTTagList_tagCount(l)==1);NBTTagCompound *p=NBTTagList_getCompoundTagAt(l,0);EnumBannerPatternArray *v=EnumBannerPattern_values(h);CHECK(v&&ordinal>=0&&ordinal<v->length);CHECK(NBTString_equals(NBTTagCompound_getString_ascii(p,"Pattern"),v->items[ordinal]->patternID));CHECK(NBTTagCompound_getInteger_ascii(p,"Color")==color);}else if(out)CHECK(TileEntityBanner_getPatterns(out)==0);
        CHECK(!MCObjectHeap_failed(h));MCObjectRootScope_end(&scope);MCObjectHeap_free(h);vectors++;
    }CHECK(feof(f));CHECK(fclose(f)==0);printf("Independent original banner vectors: %u passed\n",vectors);
}
int main(int argc,char **argv) {enums_and_roots();add_and_mutability();duplicate_and_helpers();manager_and_exception();if(argc>1)original_vectors(argv[1]);printf("Source banner recipes: %u checks passed\n",checks);return 0;}
